---
title: "Probabilistic Range Maps"
author: "Ben Best (bbest@nceas.ucsb.edu)"
date: July 23, 2014
bibliography: phd_thesis.bib
csl: ecology.csl
output:
  html_document:
    toc: true
---

# 3. Probabilistic Range Maps
Global observations of marine animals are often constrained to nearshore environments. To overcome the paucity of observations, expert-derived opinion, often in the form of drawn range maps, is enlisted for global species assessments (Schipper et al. 2008). These are binary (habitat or not habitat) without any measure of uncertainty. So little data was available for this analysis that of the 120 marine species the range of those threatened to extinction varied as widely as 23 to 61%. Ready et al. (2010) extracted simple environmental envelopes (Kaschner et al. 2006) from the literature and areas of exclusion based on range maps to produce a global distributions of cetacean and other marine taxa . We will apply a hierarchical state-space Bayes framework (Clark and Gelfand 2006; Schick et al. 2008) for mixing IUCN range maps (Schipper et al. 2008) with observational data and associated environmental data.
In areas rich in observational data, the quantitative data should overwhelm the qualitative opinion in terms of matching to environmental signal. As more data becomes available it is easily updateable.

# References