<!--- `source('make_config.R'); render_html('a_abstract.Rmd')` # run for quick render -->
# Abstract {-}

Human use of the oceans is increasingly in conflict with conservation of endangered species. Methods for managing the spatial and temporal placement of industries such as military, fishing, transportation and offshore energy, have historically been post-hoc; ie the time and place of human activity is already determined before assessment of environmental impacts. Instead, I describe a spatio-temporal decision framework that transparently optimizes the tradeoff between conservation risk and industry profit for placement of human activities in space and time. Spatially, placement is framed either as a siting or routing problem. For instance, determination of military exercises, fishing grounds and offshore pile driving get sited based on determining times and places that minimize conservation risk and industry costs. Whereas the transportation or cruise line industries need to route between destinations in a manner so as to minimize risk of encounter with endangered species as well as minimize cost of extra travel.

The reliability of this spatio-temporal decision framework depends on the input species distributions, which are inherently uncertain. Accounting for this uncertainty within the decision framework is therefore essential.

Furthermore, reduction and/or accurate description of this uncertainty is demonstrated through several methods. Where marine animal observation data are readily available from scientific surveys, data from multiple platforms can be combined so as to provide the most complete description of the species distribution. In data poor areas, expert range maps can be combined with environmental covariates to achieve a probabilistic distribution having a measure of uncertainty. Another common problem with marine environmental predictors are data gaps caused by cloud cover in remotely sensed imagery. These gaps are filled using neighboing data in space and time such that the associated uncertainty is passed along to the species distribution and decision framework. Finally, rather than the usual suspects of readily available environmental predictors, I propose a suite of comprehensive predictors that includes  distances from dominant current, sea surface temperature fronts and eddy structures. Beyond simply remotely sensed variables, oceanographic model data are used such as mixed layer depth.
